server:
  port: 10088
spring:
  datasource:
    url: jdbc:mysql://106.12.24.105:3310/zhihuiyun
    username: test
    password: test
  redis:
    host: 106.12.24.105
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

zhy:
  jwt:
    secret: zhy@Login(Auth}*^23)&zhihuiyun%f3q2 # 登录校验的密钥
    pubKeyPath: D:/zhy/ssh/id_rsa.pub # 公钥地址
    priKeyPath: D:/zhy/ssh/id_rsa.pri # 私钥地址
    expire: 10 # 过期时间,单位分钟
    cookieName: ZHY_TOKEN